### ISSUE TITLE
Copyleft bir lisansa geçiş

### ISSUE THREAD

**Issue by ooguz** [arkakapi/digital-library#22]
Merhaba,

Lisans olarak Expat/X11 lisansı tercih etmişsiniz. Bildiğiniz üzere Expat lisansı copyleft değil. Yani digital-library'nin bu lisans koşulları altında değiştirilmiş kopyaları özgür olmak zorunda değil. Özgür yazılım topluluğundaki genel lisanslama eğilimi son yıllarda GitHub etkisiyle tersini gösterse de, copyleft bir lisans kullanmak her zaman daha iyi olacaktır. Çünkü yazılımın özgürlüğü korunur ve bu kadar emek bir özel mülk yazılım geliştirici tarafından çalınmamış olur.

En yaygın copyleft lisans GNU GPL v3 olsa da, digital-library gibi çevrimiçi hizmet veren yazılımlar için AGPL v3 lisansı çok daha uygun. Çünkü GPL'den farklı olarak AGPL'de, yazılım bir ağ üzerinde kullanılıyorsa, kaynak kodu kullanıcıya verilmek zorunda. Örneğin ben digital-library'i alıp bazı değişikliklerle sanal-kutuphane olarak kullanıyorum ve bir web servisi olarak hizmet veriyorum, kaynak kodunu karşı tarafa vermek zorundayım. 

Bu sebeple, henüz geliştirici sayısı da azken, yazılımı GNU AGPL v3'e geçirmeyi öneriyorum.

Saygılarımla,

**Comment by om3rcitak** [comment]
@ooguz Selam,

Oncelikle bilgiler icin cok tesekkurler. Lisanslar konusunda biraz cahil oldugumuzdan MITde karar kilmistik lakin anlattiklarina bakinda GNU AGPL v3 mantikli gibi. Lakin bir sorum var, hali hazirda MIT ile lisanslanmis bir yazilimi GNU AGPL v3e vecirebiliyor muyuz? Bunun onunde hukuki bir engel var midir? Yok ise hemen bir pull-request gonder, senin katkin ile lisansi degistirmis olalim.

Saygilar.

**Comment by ooguz** [comment]
Bütün katkı verenlerin onayı gerekiyor sadece. Pull request açıyorum, altına iki contributor da ben onaylıyorum diye yazsın, pull request'i merge ettiğinde lisans değişmiş olacak.

**Comment by om3rcitak** [comment]
#23 ile hallettik bu meseleyi. Kapatiyorum.
