### ISSUE TITLE
centerize logo in the readme file

### ISSUE THREAD

**Issue by om3rcitak** [arkakapi/digital-library#5]

**Comment by MantieReid** [comment]
Logo Centered.  Please, If you can, accept the commit. 
https://github.com/arkakapi/digital-library/compare/master...MantieReid:patch-1

**Comment by om3rcitak** [comment]
@MantieReid thank you for contributing!

If could you do this steps, I can merge your PR.

- Centered too title.
- Remove exclamation mark before logo.
- Create pull-request.

**Comment by MantieReid** [comment]
@om3rcitak 
Exclamation mark removed. 
Closing paragraph title moved down to next line.
Centered too title. 
Pull request created. 

Done in the selected pull request linked below/. 
https://github.com/arkakapi/digital-library/compare/master...MantieReid:patch-2

Pull Request created, which you can find here  at this link. 
https://github.com/arkakapi/digital-library/pull/12

**Comment by om3rcitak** [comment]
@MantieReid I merged your pull-request! thanks!
